eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: zuul-proxy-server

server:
  port: 8080
  
  
zuul:
  routes:
    reservation-service: /api/reserve/**
    authorization-service: /api/auth/**
    web-service: /web/**