eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: zuul-proxy-server

server:
  port: 8080

security:
  oauth2:
    client:
      client-id: foo
      client-secret: bar
    resource:
      jwt:
        key-value: com.ikth.apps # 나중에 방법 찾아보자.. 일단은 key-value 프로퍼티 사용(config server)
#      token-info-uri: http://oauth2-service/oauth/check_token : 제대로 지원 안됨. 처리하려면 복잡함..
#      token-info-uri: http://localhost:8080/api/auth/oauth/check_token 필요 없음
  
zuul:
  routes:
    reservation-service: /api/reserve/**
    authorization-service: /api/auth/**
    web-service: /web/**