## TODO : UserDetails, User Service implementation  
spring:
  security:
    user:
      name: user
      password: user
      
security:
  oauth2:
    authorization:
      check-token-access: isAuthenticated()
      token-key-access: isAuthenticated()
    client:
      client-id: foo
      client-secret: bar
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
