# TODO spring config server / programmatically config

spring:
  application:
    name: reservation-service
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
server:
  port: 8762